### ISSUE TITLE
Missing refactoring: Abstract instance variables

### ISSUE THREAD

**Issue by jecisc** [Lin777/Enjoliveur#39]
https://github.com/pharo-project/pharo/issues/4194

**Comment by Ducasse** [comment]
I did a PR and it may need some more love because I could not really understand how to place the menu item. 
Now cyril let me know if it helps you for your transformation to resource usage.

**Comment by Ducasse** [comment]
https://github.com/pharo-project/pharo/pull/4199

**Comment by Lin777** [comment]
https://github.com/pharo-project/pharo/pull/4328
